{% set name = "tensorflow-text" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  #  PyPI supplies whl files for:
  # - Linux: Python 3.7, 3.8 and 3.9
  # - OS X: Python 3.7, 3.8 and 3.9
  # - Windows: Python 3.7, 3.8 and 3.9
  skip: True  # [win, osx]
  skip: True  # [py<37]
  # entry_points:
  #   - tensorboard = tensorflow.tensorboard.tensorboard:main
  script: build.sh  # [not win]

requirements:
  build:
    - python
    - pip
    - mock >=2.0.0
    - numpy
    - protobuf >=3.0.0
    - six >=1.10.0
    - wheel >=0.26
  run:
    - python
    - mock >=2.0.0
    - numpy
    - protobuf >=3.0.0
    - six >=1.10.0
    - tensorflow >=2.6.0,<2.7
    - tensorflow-hub >=0.8.0

test:
  imports:
    # Skip the import test on Linux as wheel file require a more recent
    # version of GLIBC++ than the VM used to build and test package.
    - tensorflow_text  # [not linux and not win]

about:
  home: https://github.com/tensorflow/text
  license: Apache-2.0
  summary: TensorFlow helps the tensors flow
  license_file: LICENSE
  description: |
    TF.Text is a TensorFlow library of text related ops, modules, and subgraphs. 
    The library can perform the preprocessing regularly required by text-based 
    models, and includes other features useful for sequence modeling not provided 
    by core TensorFlow.

    See the README on GitHub for further documentation. http://github.com/tensorflow/text

    PyPI: [https://pypi.org/project/tensorflow-text](https://pypi.org/project/tensorflow-text)

  doc_url: https://www.tensorflow.org/beta/tutorials/tensorflow_text/intro
  dev_url: https://github.com/tensorflow/text

extra:
  recipe-maintainers:
    - sugatoray
