{% set name = "sagemaker-training" %}
{% set version = "4.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sagemaker_training-{{ version }}.tar.gz
  sha256: ab75435d53c2e8144f54d200536d44eb361e3971e0d906b5c49837674188a512

build:
  number: 0
  noarch: python
  entry_points:
    - train=sagemaker_training.cli.train:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - boto3
    - gevent
    - inotify_simple ==1.2.1
    - numpy
    - paramiko >=2.4.2
    - pip
    - protobuf >=3.9.2,<3.20
    - psutil >=5.6.7
    - retrying >=1.3.3
    - scipy >=1.2.2
    - six
    - werkzeug >=0.15.5

test:
  imports:
    - sagemaker_training
    - sagemaker_training.cli
  commands:
    - pip check
    - train --help
  requires:
    - pip

about:
  home: https://github.com/aws/sagemaker-training-toolkit/
  summary: Open source library for creating containers to run on Amazon SageMaker.
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Open source library for creating containers to run on Amazon SageMaker.

    PyPI: [https://pypi.org/project/sagemaker-training/](https://pypi.org/project/sagemaker-training/)

  doc_url: https://github.com/aws/sagemaker-training-toolkit/
  dev_url: https://github.com/aws/sagemaker-training-toolkit/

extra:
  recipe-maintainers:
    - sugatoray
