{% set name = "skyplane" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skyplane-{{ version }}.tar.gz
  sha256: fc7aabbad5518469deba0e017032043d8df73735664468ff21ae9c99efb4f369

build:
  number: 0
  noarch: python
    entry_points:
    - skylark = skyplane.cli.cli:app
    - skyplane = skyplane.cli.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.11
    # necessary for build-tools (see pyproject.toml in upstream source)
    - setuptools
    - poetry-core >=1.0.0
  run:
    - python >=3.6,<3.11
    - azure-identity >=1,<2
    - azure-mgmt-authorization >=1.0.0
    - azure-mgmt-compute >=24.0.0
    - azure-mgmt-network >=10.0.0
    - azure-mgmt-resource >=11.0.0
    - azure-mgmt-storage >=11.0.0
    - azure-storage-blob >=12.0.0
    - boto3 >=1.16.0
    - cachetools >=4.1.0
    - click >=8.0.0
    - google-api-python-client >=2.0.2
    - google-auth >=2.0.0
    - google-cloud-compute >=1.0.0
    - google-cloud-storage >=1.30.0
    - pandas >=1.0.0
    - paramiko >=2.7.2
    - rich >=9.0.0
    - sshtunnel >=0.3.0
    - typer >=0.4.0

test:
  imports:
    - skyplane
  commands:
    - pip check
    - skylark --help
    - skyplane --help
  requires:
    - pip

about:
  home: https://skyplane.org/
  summary: Skyplane efficiently transports data between cloud regions and providers.
  license: Apache-2.0
  license_file:
    - LICENSE
  description: |
    :fire: **Blazing fast bulk data transfers between any cloud** :fire:

    Skyplane is a tool for blazingly fast bulk data transfers in the cloud. 
    Skyplane manages parallelism, data partitioning, and network paths to 
    optimize data transfers, and can also spin up VM instances to increase 
    transfer throughput.

    PyPI: [https://pypi.org/project/skyplane/](https://pypi.org/project/skyplane/)

  doc_url: https://skyplane.org/en/latest/
  dev_url: https://github.com/skyplane-project/skyplane

extra:
  recipe-maintainers:
    - sugatoray
