{% set name = "omnixai" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/omnixai-{{ version }}.tar.gz
  sha256: 0940a160be9265d9bfc00f3a6a7019cc05e40afcb77b0ad489ee61114b9f989d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - dill
    - hnswlib >=0.5.0
    - ipython
    - lime
    - matplotlib-base
    - numpy >=1.17
    - packaging
    - pandas >=1.1.0
    - pillow <10.0
    - salib
    - scikit-image >=0.17.2
    - scikit-learn >=0.24,<1.2
    - scipy >=1.5.0
    - shap >=0.40.0
    - statsmodels >=0.10.1
    - tabulate
    - tqdm
    - wheel

test:
  imports:
    - docs
    - omnixai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/salesforce/omnixai
  summary: "OmniXAI: An Explainable AI Toolbox"
  license: BSD-3-Clause
  license_file:
    - LICENSE
  description: |
    OmniXAI (short for Omni eXplainable AI) is a Python machine-learning library 
    for explainable AI (XAI), offering omni-way explainable AI and interpretable 
    machine learning capabilities to address many pain points in explaining 
    decisions made by machine learning models in practice. OmniXAI aims to be a 
    one-stop comprehensive library that makes explainable AI easy for data scientists, 
    ML researchers and practitioners who need explanation for various types of data, 
    models and explanation methods at different stages of ML process.

    [![banner][_image]](https://github.com/salesforce/omnixai)

    [_image]: https://github.com/salesforce/OmniXAI/raw/main/docs/_static/ml_pipeline.png

    PyPI: [https://pypi.python.org/pypi/omnixai](https://pypi.python.org/pypi/omnixai)

  doc_url: https://opensource.salesforce.com/OmniXAI
  dev_url: https://github.com/salesforce/omnixai

extra:
  recipe-maintainers:
    - sugatoray
