{% set name = "pmlb" %}
{% set version = "1.0.1.post3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pmlb-{{ version }}.tar.gz
  sha256: ff1195abf0b54f2e06ea8f30c95a746e6561c5d5e01ef83950158cb7ff58a315

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pandas >=1.0.5
    - pyyaml >=5.3.1
    - requests >=2.24.0

test:
  imports:
    - pmlb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/EpistasisLab/penn-ml-benchmarks
  summary: A Python wrapper for the Penn Machine Learning Benchmark data repository.
  license: MIT
  license_file: LICENSE
  describe: |
    A Python wrapper for the Penn Machine Learning Benchmark data repository.

    PyPI: [https://pypi.org/project/pmlb](https://pypi.org/project/pmlb)

  doc_url: https://github.com/EpistasisLab/penn-ml-benchmarks
  dev_url: https://github.com/EpistasisLab/penn-ml-benchmarks

extra:
  recipe-maintainers:
    - sugatoray
