{% set name = "txtai" %}
{% set version = "4.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txtai-{{ version }}.tar.gz
  sha256: 0cb87b255818f3ae058e73db654ee6ab3fde1aeecb139765b38f066859bc6faa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    # necessary for passing pip-check
    - faiss-cpu >=1.7.1.post2
  run:
    - python >=3.7
    - faiss-cpu >=1.7.1.post2
    - numpy >=1.18.4
    - pyyaml >=5.3
    - pytorch >=1.6.0
    - transformers >=4.20.1

test:
  imports:
    - txtai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neuml/txtai
  summary: Build AI-powered semantic search applications
  license: Apache-2.0
  license_file:
    - LICENSE
  description: |
    txtai executes machine-learning workflows to transform data and build 
    AI-powered semantic search applications.

    [![banner][_image]](https://github.com/neuml/txtai)

    [_image]: https://raw.githubusercontent.com/neuml/txtai/master/demo.gif

    PyPI: [https://pypi.python.org/pypi/txtai](https://pypi.python.org/pypi/txtai)

  doc_url: https://neuml.github.io/txtai
  dev_url: https://github.com/neuml/txtai

extra:
  recipe-maintainers:
    - sugatoray
