{% set name = "hpsklearn" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a320062eb3296b35cccac87ad8b28b95dbc5f1fad22dc81e911f26d5b491cb7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - hyperopt
    - nose
    - numpy    
    - scikit-learn
    - scipy

test:
  imports:
    - hpsklearn
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://hyperopt.github.com/hyperopt-sklearn/
  summary: Hyperparameter Optimization for sklearn
  license: BSD-4-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sugatoray
