{% set name = "rasa-sdk" %}
{% set version = "3.0.2" %}
{% set build_num = 0 %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 665282c07e3bc93dc857b2944707d66159bf585af69b0e411a365f9cbba7829e
  

build:
  skip: True  # [osx or win]
  number: {{ build_num }}

outputs:
  - name: {{ name|lower }}    
    build:
      skip: True  # [osx or win]
      noarch: python
    script: build_base.sh
    requirements:
      {% set pyver = ">=3.7,<3.10" %}
      host:
        - pip
        - python {{ pyver }}
        - poetry-core >=1.0.0
      run:
        - python {{ pyver }}
        - poetry-core >=1.0.0
        # Dependency Source: PKG-INFO:Requires-Dist
        - Sanic-Cors >=1.0.0,<2.0.0
        - coloredlogs >=10,<16
        - requests >=2.23.0,<2.26.0
        - sanic >=21.6.0,<22.0.0
        - typing-extensions >=3.7.4,<4.0.0
        - urllib3 >=1.26.5,<2.0.0
        - uvloop <0.15.0  # [not win32]
      #run_constrained:
        
    test:
      imports:
        - {{ name|lower }}
      commands:
        - pip check
      requires:
        - pip


about:
  home: https://rasa.com/
  summary: |
    Python SDK for the development of custom actions for Rasa.
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |
    Open source machine learning framework to automate text 
    and voice-based conversations: NLU, dialogue management, 
    connect to Slack, Facebook, and more - Create chatbots 
    and voice assistants.    
  doc_url: https://rasa.com/docs
  dev_url: https://github.com/RasaHQ/rasa-sdk/

extra:
  recipe-maintainers:
    - sugatoray
    #- koaning
    #- tmbo
  feedstock-name: {{ name|lower }}
