{% set name = "storm-tuner" %}
{% set version = "0.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/storm-tuner-{{ version }}.tar.gz
  sha256: ba4ab721594550dd4413ec25062eb4278367de79bd83f5870273d8e00baba82e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - storm_tuner
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ben-arnao/StoRM
  summary: Neural network hyperparameter tuner
  license: Apache-2.0
  license_file: LICENSE
  description: |
    ## StoRM (Stochastic Random Mutator)
    
    A robust hyperparameter tuner for high-dimensional, categorically and/or 
    conditionally-parameterized, intractable optimization problems (Ex. Neural Network).


    PyPI: [https://pypi.org/project/storm-tuner/](https://pypi.org/project/storm-tuner/)

  doc_url: https://github.com/ben-arnao/StoRM
  dev_url: https://github.com/ben-arnao/StoRM

extra:
  recipe-maintainers:
    - sugatoray
