{% set name = "whatlies" %}
{% set version = "0.6.5" %}
{% set build_num = 0 %}
{% set name_ = name|lower %}

######### SET DEPENDENCY VERSION REQUIREMENTS #########

{% set pyver = ">=3.6,<3.8" %}

# base_packages
{% set libver_altair = ">=4.0.1" %} 
{% set libver_bpemb = ">=0.3.0" %}
{% set libver_gensim = "~=3.8.3" %}
{% set libver_matplotlib_base = ">=3.2.0" %}
{% set libver_scikit_learn = ">=0.24.0" %}

# umap_packages
{% set libver_umap_learn = ">=0.4.0" %}
# rasa_packages
{% set libver_rasa = ">=2.7.0" %}
# fasttext_packages
{% set libver_fasttext = "~=0.9.1" %}
# spacy_packages
{% set libver_spacy = ">=3.0.1" %}
{% set libver_spacy_lookups_data = ">=0.3.2" %}
# s2v_packages (+= spacy_packages)
{% set libver_sense2vec = ">=1.0.2" %}
# tf_packages
{% set libver_tensorflow = ">=2.3.0,<2.5" %}
{% set libver_tensorflow_text = ">=2.3.0" %}
{% set libver_tensorflow_hub = ">=0.8.0" %}
# transformers_dep
{% set libver_transformers = ">=4.3.0" %}
# sentence_tfm_dep
{% set libver_sentence_transformers = ">=0.3.8" %}

#######################################################


package:
  name: {{ name_ }}-meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b97c2b5b0bbc5c4044278ea8b2d3222cbb125e1fbf7bd854bb7f09b557e13d7

build:
  number: {{ build_num }}

outputs:
  - name: {{ name_ }}
    build:
      noarch: python
    script: build_base.sh
    requirements:
      host:
        - pip
        - python {{ pyver }}
      run:
        - python {{ pyver }}
        # base_packages
        - altair {{ libver_altair }}
        - bpemb {{ libver_bpemb }}
        - gensim {{ libver_gensim }}
        - matplotlib-base {{ libver_matplotlib_base }}
        - scikit-learn {{ libver_scikit_learn }}
      run_constrained:
        # umap_packages
        - umap-learn {{ libver_umap_learn }}
        # rasa_packages
        - rasa {{ libver_rasa }}
        # fasttext_packages
        - fasttext {{ libver_fasttext }}
        # spacy_packages
        - spacy {{ libver_spacy }}
        - spacy-lookups-data {{ libver_spacy_lookups_data }}
        # s2v_packages (+= spacy_packages)
        - sense2vec {{ libver_sense2vec }}
        # tf_packages
        - tensorflow {{ libver_tensorflow }}
        - tensorflow-text {{ libver_tensorflow_text }}
        - tensorflow-hub {{ libver_tensorflow_hub }}
        # transformers_dep
        - transformers {{ libver_transformers }}
        # sentence_tfm_dep
        - sentence-transformers {{ libver_sentence_transformers }}
    test:
      imports:
        - {{ name_ }}
      commands:
        - pip check
      requires:
        - pip

  # umap_packages
  - name: {{ name_ }}-umap
    build:
      noarch: generic
      string: {{ build_num }}_{{ "umap" }}_extra
    requirements:
      run:
        # RECIPE: 
        # "umap": base_packages + umap_packages
        - {{ name_ }} {{ version }}
        - umap-learn {{ libver_umap_learn }}
    test:
      imports:
        - {{ name_ }}
      commands:
        - pip check
      requires:
        - pip

  # rasa_packages
  - name: {{ name_ }}-rasa
    build:
      noarch: generic
      string: {{ build_num }}_{{ "rasa" }}_extra
    requirements:
      run:
        # RECIPE: 
        # "rasa": base_packages + rasa_packages
        - {{ name_ }} {{ version }}
      run_constrained:
        # using run_constrained temporarily
        # until rasa is made available on
        # conda-forge channel.
        - rasa {{ libver_rasa }}
    test:
      imports:
        - {{ name_ }}
      commands:
        - pip check
      requires:
        - pip

  # fasttext_packages
  - name: {{ name_ }}-fasttext
    build:
      noarch: generic
      string: {{ build_num }}_{{ "fasttext" }}_extra
    requirements:
      run:
        # RECIPE: 
        # "fasttext": base_packages + fasttext_packages
        - {{ name_ }} {{ version }}
        - fasttext {{ libver_fasttext }}
    test:
      imports:
        - {{ name_ }}
      commands:
        - pip check
      requires:
        - pip

  # spacy_packages
  - name: {{ name_ }}-spacy
    build:
      noarch: generic
      string: {{ build_num }}_{{ "spacy" }}_extra
    requirements:
      run:
        # RECIPE: 
        # "spacy": base_packages + spacy_packages
        - {{ name_ }} {{ version }}
        - spacy {{ libver_spacy }}
        - spacy-lookups-data {{ libver_spacy_lookups_data }}
    test:
      imports:
        - {{ name_ }}
      commands:
        - pip check
      requires:
        - pip

  # s2v_packages
  - name: {{ name_ }}-sense2vec
    build:
      noarch: generic
      string: {{ build_num }}_{{ "sense2vec" }}_extra
    requirements:
      run:
        # RECIPE: 
        # s2v_packages = ["sense2vec>=1.0.2"] + spacy_packages
        # "sense2vec": base_packages + s2v_packages
        - {{ pin_subpackage(name_ ~ "-spacy", exact=True) }}
        - sense2vec {{ libver_sense2vec }}
    test:
      imports:
        - {{ name_ }}
      commands:
        - pip check
      requires:
        - pip

  # tf_packages
  - name: {{ name_ }}-tfhub
    build:
      noarch: generic
      string: {{ build_num }}_{{ "tfhub" }}_extra
    requirements:
      run:
        # RECIPE: 
        # "tfhub": base_packages + tf_packages
        - {{ name_ }} {{ version }}
        - tensorflow {{ libver_tensorflow }}
        - tensorflow-text {{ libver_tensorflow_text }}
        - tensorflow-hub {{ libver_tensorflow_hub }}
    test:
      imports:
        - {{ name_ }}
      commands:
        - pip check
      requires:
        - pip

  # transformers_dep
  - name: {{ name_ }}-transformers
    build:
      noarch: generic
      string: {{ build_num }}_{{ "transformers" }}_extra
    requirements:
      run:
        # RECIPE: 
        # "transformers": base_packages + transformers_dep
        - {{ name_ }} {{ version }}
        - transformers {{ libver_transformers }}
    test:
      imports:
        - {{ name_ }}
      commands:
        - pip check
      requires:
        - pip

  # sentence_tfm_dep
  - name: {{ name_ }}-sentence_tfm
    build:
      noarch: generic
      string: {{ build_num }}_{{ "sentence_tfm" }}_extra
    requirements:
      run:
        # RECIPE: 
        # "transformers": base_packages + sentence_tfm_dep
        - {{ name_ }} {{ version }}
        - sentence-transformers {{ libver_sentence_transformers }}
        # sentence-transformers 2.0.0 requires torchvision
        # remove torchvision once PR#https://github.com/conda-forge/sentence-transformers-feedstock/pull/21
        # is merged and this issue is resolved.
        - torchvision
    test:
      imports:
        - {{ name_ }}
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://rasahq.github.io/whatlies/
  summary: Tools to help uncover `whatlies` in word embeddings.
  license: Apache-2.0
  license_file: LICENSE
  description: |
    This small library offers tools to make visualisation 
    easier of both word embeddings as well as operations 
    on them.
  doc_url: https://rasahq.github.io/whatlies/
  dev_url: https://github.com/RasaHQ/whatlies/

extra:
  recipe-maintainers:
    - sugatoray
    #- koaning
  feedstock-name: {{ name_ }}
