{% set name = "super-gradients" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Deci-AI/super-gradients/archive/{{ version }}.tar.gz
  sha256: c0ba465bb61aa51c510d981f10719a8bf73c91e3e2107edc0b319b12ce5a6004

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - boto3 >=1.17.15
    - coverage >=5.3.1,<5.4.0
    - deprecated >=1.2.11
    - einops ==0.3.2
    - hydra-core
    - jsonschema >=3.2.0
    - matplotlib-base >=3.3.4
    - omegaconf
    - onnx >=1.10.1
    - onnxruntime
    - opencv >=4.5.1
    - packaging >=20.4
    - pillow >=6.2.0
    - pip-tools >=6.4.0
    - protobuf >=3.19.0,<3.20.0
    - psutil >=5.8.0
    - pycocotools ==2.0.4
    - pyparsing ==2.4.5
    - scipy >=1.6.1
    - setuptools >=21.0.0
    - sphinx >=4.0.2,<4.1.0
    - sphinx_rtd_theme
    - tensorboard >=2.4.1
    - termcolor ==1.1.0
    - pytorch >=1.9.0
    - torchmetrics ==0.8
    - torchvision >=0.10.0
    - tqdm >=4.57.0
    - treelib ==1.6.1
  run_constrained: 
    # deci-lab-client only has .whl file on PyPI and 
    # the GitHub repo is private.
    - deci-lab-client ==2.38.0

test:
  imports:
    - super_gradients
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.supergradients.com/
  summary: Easily train or fine-tune SOTA computer vision models with one open source training library
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - documentation/source/LICENSE.md
  description: |
    [![banner][_banner]](https://github.com/Deci-AI/super-gradients)

    [_banner]: https://github.com/Deci-AI/super-gradients/raw/master/docs/assets/SG_img/SG%20-%20Horizontal.png

    Welcome to SuperGradients, a free, open-source training library for PyTorch-based 
    deep learning models. SuperGradients allows you to train or fine-tune SOTA pre-trained 
    models for all the most commonly applied computer vision tasks with just one training 
    library. We currently support object detection, image classification and semantic 
    segmentation for videos and images.

    PyPI: [https://pypi.org/project/super-gradients](https://pypi.org/project/super-gradients)

  doc_url: https://deci-ai.github.io/super-gradients/welcome.html
  dev_url: https://github.com/Deci-AI/super-gradients

extra:
  recipe-maintainers:
    - sugatoray
