{% set name = "aiqc" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiqc-{{ version }}.tar.gz
  sha256: a337f39ab75e0c29843080f10ebaaa1a96aea35168e9f32d74f4c2ec874f190a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5,<3.9
  run:
    - python >=3.5,<3.9
    - appdirs >=1.4.4
    - dill >=0.3.3
    - fastparquet >=0.7.1
    - fsspec >=0.9.0
    - h5py >=3.6.0
    - keras >=2.7.0
    - natsort >=7.1.1
    - numpy >=1.19.5
    - pandas >=1.1.0
    - peewee >=3.14.3
    - pillow >=8.1.2
    - plotly >=5.3.1
    - pyarrow >=3.0.0
    - scikit-learn >=0.24.1
    - tensorflow >=2.7.0
    - pytorch >=1.8.1
    - torchmetrics >=0.2.0
    - tqdm >=4.59.0
    - validators >=0.18.2

test:
  imports:
    - aiqc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aiqc.readthedocs.io/
  summary: End-to-end machine learning on your desktop or server.
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    AIQC accelerates research teams with an open source framework for deep learning pipelines.

    *A simple Python framework for conducting rapid, rigorous, and reproducible experiments.*

    PyData Global 2021 Video Demo of AIQC :sparkles:
    - YouTube Video: youtube.com/watch?v=XlQGqYkL8N4

    PyPI: [https://pypi.org/project/aiqc/](https://pypi.org/project/aiqc/)

  doc_url: https://aiqc.readthedocs.io/
  dev_url: https://github.com/aiqc/AIQC

extra:
  recipe-maintainers:
    - sugatoray
