{% set name = "jill" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jill-{{ version }}.tar.gz
    sha256: 48ea86a508f87dab0293d00634b4e8c6677cb00676e617b6c46345bc10af5e10
  #- url: https://raw.githubusercontent.com/johnnychen94/jill.py/master/requirements.txt

build:
  number: 0
  noarch: python
  script: 
    ## Ensure inclusion of requirements.txt
    {% set reqfile = "requirements.txt" %}
    {% set reqsource = name ~ ".egg-info/requires.txt" %}
    # IF {{ reqfile }} is NOT PRESENT, COPY {{ reqfile }} from {{ reqsource }}
    - echo -e "\n>>> ENSURE INCLUSION OF '{{ reqfile }}' <<<\n\n"
    - if [ ! -f {{ reqfile }} ] && [ -f {{ reqsource }} ]; then cp {{ reqsource }} {{ reqfile }}; fi  # [not win]
    #- copy {{ name }}.egg-info\requires.txt {{ reqfile }}  # [win]
    - copy {{ reqsource | replace('/', '\\') }} {{ reqfile }}  # [win]
    ## Install package
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - wget
  run:
    - python >=3.6
    - fire
    - jsonschema
    - python-gnupg
    - requests
    - requests-futures
    - semantic_version
    - wget

test:
  imports:
    - jill
  commands:
    - pip check
  requires:
    - pip
    # wget is necessary for passing pip-check
    # despite adding it under run-requirements.
    - wget

about:
  home: https://github.com/johnnychen94/jill.py
  summary: JILL -- Julia Installer for Linux (MacOS, Windows and FreeBSD) -- Light
  license: MIT
  license_file: LICENSE
  description: |
    The enhanced Python fork of JILL -- Julia Installer for Linux 
    (and every other platform) -- Light.

    **Features**

    - download Julia releases from the *nearest* mirror server
    - support all platforms and architectures
    - manage multiple julia releases
    - easy-to-use CLI tool

    Cross Platform Installtion of Julia: https://julialang.org/downloads/platform/#cross-platform_installer

    PyPI: [https://pypi.org/project/jill/](https://pypi.org/project/jill/)

  doc_url: https://github.com/johnnychen94/jill.py
  dev_url: https://github.com/johnnychen94/jill.py

extra:
  recipe-maintainers:
    - sugatoray
