{% set name = "jill" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jill-{{ version }}.tar.gz
    sha256: 17328a3769f3975018257e98d1b23c6caaed07a73c6c35947df4aebdef206b3f

build:
  number: 0
  noarch: python
  entry_points:
    - jill=jill.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - fire
    - jsonschema
    - python-gnupg
    - requests
    - requests-futures
    - semantic_version
    - wget

test:
  imports:
    - jill
  # commands:
  #   - jill --help  

about:
  home: https://github.com/johnnychen94/jill.py
  summary: JILL -- Julia Installer for Linux (MacOS, Windows and FreeBSD) -- Light
  license: MIT
  license_file: LICENSE
  description: |
    The enhanced Python fork of JILL -- Julia Installer for Linux 
    (and every other platform) -- Light.

    **Features**

    - download Julia releases from the *nearest* mirror server
    - support all platforms and architectures
    - manage multiple julia releases
    - easy-to-use CLI tool

    Cross Platform Installtion of Julia: https://julialang.org/downloads/platform/#cross-platform_installer

    PyPI: [https://pypi.org/project/jill/](https://pypi.org/project/jill/)

  doc_url: https://github.com/johnnychen94/jill.py
  dev_url: https://github.com/johnnychen94/jill.py

extra:
  recipe-maintainers:
    - sugatoray
