{% set name = "augmenty" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/augmenty-{{ version }}.tar.gz
  sha256: 9c20f234c7eb1b4948643976d39cd4b4da113fc60d6b2e2b7343059e0f969842

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - spacy >=3.2.0,<3.3.0

test:
  imports:
    - augmenty
    - demo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/KennethEnevoldsen/augmenty
  summary: An augmentation library based on SpaCy for joint augmentation of text and labels.
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Augmenty is an augmentation library based on spaCy for augmenting texts. 
    Besides a wide array of highly flexible augmenters, Augmenty provides a 
    series of tools for working with augmenters, including combining and 
    moderating augmenters. Augmenty differs from other augmentation libraries 
    in that it corrects (as far as possible) the assigned labels under the 
    augmentation, thus making many of the augmenters valid for training in 
    a wider range of tasks.

    PyPI: [https://pypi.org/project/augmenty/](https://pypi.org/project/augmenty/)

  doc_url: https://kennethenevoldsen.github.io/augmenty/
  dev_url: https://github.com/KennethEnevoldsen/augmenty

extra:
  recipe-maintainers:
    - sugatoray
