{% set name = "pypots" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wenjiedu/pypots/archive/v{{ version }}.tar.gz
  sha256: 4a2e4b2045a363dbe38b459f82d0ffce38442d6c49f16ec29affe736732fb5a1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools >=38.6.0
    - python >=3.7
  run:
    - python >=3.7
    - matplotlib-base
    - numpy
    - pandas
    - scikit-learn
    - scipy
    - tensorboard
    - pytorch >=1.10
    - torch-scatter
    - pytorch_geometric
    - pytorch_sparse ==0.6.13
    - tsdb
  run_constrained:
    # no source available on PyPI
    # no release available on GitHub
    - pycorruptor

test:
  imports:
    - pypots
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/WenjieDu/PyPOTS
  summary: A Python Toolbox for Data Mining on Partially-Observed Time Series
  license: GPL-3.0-only
  license_file:
    - LICENSE
  description: |
    A Python Toolbox for Data Mining on Partially-Observed Time Series.

    PyPI: [https://pypi.org/project/pypots](https://pypi.org/project/pypots)

  doc_url: https://github.com/WenjieDu/PyPOTS
  dev_url: https://github.com/WenjieDu/PyPOTS

extra:
  recipe-maintainers:
    - sugatoray
