{% set name = "pyleniumio" %}
{% set version = "1.12.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyleniumio-{{ version }}.tar.gz
  sha256: d05e4b2b83893db863b976b304aa55e40dd8cb2b558e66e3390c0c318f6586fd

build:
  number: 0
  noarch: python
  entry_points:
    - pylenium=pylenium.scripts.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    #- pylenium-cli
    - python >=3.6
    - poetry
  run:
    - python >=3.6
    - axe-selenium-python
    - click
    - faker
    - pydantic
    - pyfiglet
    - pytest
    - pytest-parallel
    - pytest-reportportal
    - pytest-xdist    
    - requests
    - selenium
    - webdriver-manager

test:
  imports:
    - pylenium
    - pylenium.scripts
  commands:
    - pip check
    - pylenium --help
  requires:
    - pip

about:
  home: https://github.com/ElSnoMan/pyleniumio
  summary: The best of Selenium and Cypress in a single Python Package
  license: MIT
  license_file: LICENSE
  description: |
    ## The mission of Pyleniumio

    > Bring the best of Selenium, Cypress and Python into one package.

    This means:

    * Automatic waiting and synchronization
    * Quick setup to start writing tests
    * Easy to use and clean syntax for amazing readability and maintainability
    * Automatic driver installation so you don't need to manage drivers
    * Leverage the awesome Python language
    * and more!
  doc_url: https://elsnoman.gitbook.io/pylenium
  dev_url: https://github.com/ElSnoMan/pyleniumio

extra:
  recipe-maintainers:
    - sugatoray
