{% set name = "kmodes" %}
{% set version = "0.12.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kmodes-{{ version }}.tar.gz
  sha256: 1ed5c2bee2501974c0766f9816f3baf70c2c71d8c9053e65474ecc977d39023e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - joblib >=0.11
    - numpy >=1.10.4
    - python >=3.6
    - scikit-learn >=0.22.0
    - scipy >=0.13.3

test:
  imports:
    - kmodes
    - kmodes.util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nicodv/kmodes
  summary: Python implementations of the k-modes and k-prototypes clustering algorithms for clustering categorical data.
  license: MIT
  license_file: LICENSE
  description: |
    Python implementations of the k-modes and k-prototypes clustering algorithms. 
    Relies on numpy for a lot of the heavy lifting.

    k-modes is used for clustering categorical variables. It defines clusters based 
    on the number of matching categories between data points. (This is in contrast 
    to the more well-known k-means algorithm, which clusters numerical data based 
    on Euclidean distance.) The k-prototypes algorithm combines k-modes and k-means 
    and is able to cluster mixed numerical / categorical data.

    PyPI: [https://pypi.python.org/pypi/kmodes/](https://pypi.python.org/pypi/kmodes/)

  doc_url: https://github.com/nicodv/kmodes
  dev_url: https://github.com/nicodv/kmodes

extra:
  recipe-maintainers:
    - sugatoray
