{% set name = "quantulum3" %}
{% set version = "0.7.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quantulum3-{{ version }}.tar.gz
  sha256: 8ac9664734133d7c3ff2796d69f64440e4ab424ced98f791b34a86e86d87b352

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - inflect
    - num2words
    - python >=3.6

test:
  imports:
    - quantulum3
    - quantulum3._lang
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nielstron/quantulum3
  summary: Extract quantities from unstructured text.
  license: MIT
  license_file: LICENSE
  description: |
    Python library for information extraction of quantities, measurements
    and their units from unstructured text. It is able to disambiguate between similar
    looking units based on their *k-nearest neighbours* in their 
    [GloVe](https://nlp.stanford.edu/projects/glove/) vector representation
    and their [Wikipedia](https://en.wikipedia.org/) page.

    This is the Python 3 compatible fork of [recastrodiaz\'
    fork](https://github.com/recastrodiaz/quantulum) of [grhawks\'
    fork](https://github.com/grhawk/quantulum) of [the original by Marco
    Lagi](https://github.com/marcolagi/quantulum).
    The compatibility with the newest version of sklearn is based on
    the fork of [sohrabtowfighi](https://github.com/sohrabtowfighi/quantulum).

    PyPI: [https://pypi.org/project/quantulum3/](https://pypi.org/project/quantulum3/)

  doc_url: https://github.com/nielstron/quantulum3
  dev_url: https://github.com/nielstron/quantulum3

extra:
  recipe-maintainers:
    - sugatoray
