{% set name = "selectolax" %}
{% set version = "0.3.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/selectolax-{{ version }}.tar.gz
  sha256: d71d7ae7bec6e856b83111f270bc783e531d86e02ad3a78a37d8591ff8f3620f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython >=0.29.23
    - pip
    - python
  run:
    - python

test:
  imports:
    - selectolax
  commands:
    - pip check
  requires:
    - pip
    ## Note: 
    #  this is needed to make pip check pass 
    #  even though cython isn't actually needed 
    #  at runtime.
    - cython >=0.29.23

about:
  home: https://github.com/rushter/selectolax
  summary: Fast HTML5 parser with CSS selectors.
  license: MIT
  license_file: LICENSE
  description: |
    A fast HTML5 parser with CSS selectors using [Modest](https://github.com/lexborisov/Modest/)
    and [Lexbor](https://github.com/lexbor/lexbor) engines.

    See the detailed overview here: [walkthrough notebook][_walkthrough].
    
    [_walkthrough]: https://github.com/rushter/selectolax/blob/master/examples/walkthrough.ipynb

    PyPI: <https://pypi.org/project/selectolax/>

  doc_url: https://github.com/rushter/selectolax
  dev_url: https://github.com/rushter/selectolax

extra:
  recipe-maintainers:
    - sugatoray
