{% set name = "dbias" %}
{% set version = "0.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Dbias-{{ version }}.tar.gz
  sha256: aef54d5d208886611c074598be3e9f9f1fc32d485003c0c6cd6c2f2352055fdd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.19.5
    - pandas >=1.2.4
    - python >=3.6
    - spacy >=3.2.1
    - tensorflow >=2.4.1
    - transformers >=4.6.1

test:
  imports:
    - Dbias
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dreji18/Fairness-in-AI
  summary: Detect, Recognize and de-bias textual data.
  license: MIT
  license_file: LICENSE
  description: |
    Detecting Bias and ensuring Fairness in AI solutions.

  doc_url: https://github.com/dreji18/Fairness-in-AI
  dev_url: https://github.com/dreji18/Fairness-in-AI

extra:
  recipe-maintainers:
    - sugatoray
