{% set name = "whylogs-sketching" %}
{% set version = "3.4.1.dev2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/whylogs-sketching-{{ version }}.tar.gz
  sha256: 0b0dc9c43e0d6a87924a45a95b922402c44600527bd22affb7eeab4a4a697936

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - cmake >=3.12
    - {{ compiler('cxx') }}
  host:
    - pip
    - python >=3.7
    - pybind11-global >=2.6.0
  run:
    - python >=3.7

test:
  imports:
    - whylogs_sketching
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/whylabs/whylogs-sketching
  summary: sketching library of whylogs
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  description: |
    A sketching library of whylogs.

    > NOTE: The GitHub repository is a private repository.

    PyPI: [https://pypi.org/project/whylogs-sketching/](https://pypi.org/project/whylogs-sketching/)

extra:
  recipe-maintainers:
    - sugatoray
