{% set name = "raiutils" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/raiutils-{{ version }}.tar.gz
  sha256: 1686dfae2ed59ccadb69ce5957b753be352ead42e87559c24223c3dfd055b703

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pandas
    - requests
    - scikit-learn
    - scipy

test:
  imports:
    - raiutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/responsible-ai-widgets
  summary: Common basic utilities used across various RAI tools
  license: MIT
  license_file: LICENSE
  description: |
    **Responsible AI Toolbox**: `{{ name | lower }}`

    Responsible AI is an approach to assessing, developing, and deploying AI systems in a safe,
    trustworthy, and ethical manner, and take responsible decisions and actions.

    Responsible AI Toolbox is a suite of tools providing a collection of model and data exploration
    and assessment user interfaces and libraries that enable a better understanding of AI systems.
    These interfaces and libraries empower developers and stakeholders of AI systems to develop and
    monitor AI more responsibly, and take better data-driven actions.

    - `{{ name | lower }}` is one of the tools of RAI Toolbox.

    <p align="center">
    <img src="https://raw.githubusercontent.com/microsoft/responsible-ai-widgets/main/img/responsible-ai-toolbox.png" alt="ResponsibleAIToolboxOverview" width="750"/>

    PyPI: [https://pypi.org/project/{{ name | lower }}/](https://pypi.org/project/{{ name | lower }}/)

    ---

    > The conda-forge recipe was made with [CondaForger App](https://sugatoray-conda-forger.streamlit.app/).

extra:
  recipe-maintainers:
    - sugatoray
