{% set name = "farm-haystack" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/farm-haystack-{{ version }}.tar.gz
  sha256: e45c9e7b02098edbed83565d2448c0acb42b9865b030eab5ea2b39c744eb00a2

build:
  number: 0
  skip: true   # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - coverage
    - dataclasses-json
    - dill
    - elastic-apm
    - elasticsearch >=7.7,<=7.10
    - faiss-cpu >=1.6.3
    - fastapi
    - gunicorn
    - httptools
    - langdetect
    - mlflow <=1.13.1
    - mmh3
    - more-itertools
    - networkx
    - nltk
    - pandas
    - pdf2image ==1.14.0
    - pillow ==8.3.2
    - psutil
    - psycopg2-binary  # [not win and not cygwin]
    - pymilvus
    - pytesseract ==0.3.7
    - python-docx
    - python-multipart
    - quantulum3
    - ray-default ==1.5.0
    - requests
    - scipy >=1.3.2
    - sentence-transformers >=0.4.0
    - seqeval
    - setuptools
    - scikit-learn
    - sparqlwrapper
    - sqlalchemy >=1.4.2
    - sqlalchemy-utils
    - tika
    - pytorch >1.5,<1.11
    - tox
    - tqdm
    - transformers ==4.7.0
    - uvicorn
    - uvloop ==0.14  # [not win and not cygwin]
    - weaviate-client ==2.5.0
    - wheel
  run_constrained:
    # Note:
    # conda install -c microsoft azure-ai-formrecognizer
    - azure-ai-formrecognizer ==3.2.0b2

test:
  imports:
    - haystack
    - haystack.document_stores
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepset-ai/haystack
  summary: Neural Question Answering & Semantic Search at Scale. Use modern transformer based models like BERT to find answers in large document collections
  license: Apache-2.0
  license_file: LICENSE
  description: |
    <p align="center">
      <a href="https://www.deepset.ai/haystack/">
        <img src="https://raw.githubusercontent.com/deepset-ai/haystack/master/docs/_src/img/haystack_logo_colored.png" alt="Haystack" />
      </a>
    </p>

    Haystack is an end-to-end framework that enables you to build powerful and 
    production-ready pipelines for different search use cases.
    Whether you want to perform Question Answering or semantic document search, 
    you can use the State-of-the-Art NLP models in Haystack to provide unique 
    search experiences and allow your users to query in natural language.
    Haystack is built in a modular fashion so that you can combine the best 
    technology from other open-source projects like Huggingface's Transformers, 
    Elasticsearch, or Milvus.

    <p align="center"><img src="https://raw.githubusercontent.com/deepset-ai/haystack/master/docs/_src/img/main_example.gif"></p>

    PyPI: [https://pypi.org/project/farm-haystack/](https://pypi.org/project/farm-haystack/)

    ## Installation

    ```sh
    conda install -c conda-forge -c microsoft farm-haystack azure-ai-formrecognizer
    ```

  doc_url: https://deepset.ai/haystack
  dev_url: https://github.com/deepset-ai/haystack

extra:
  recipe-maintainers:
    - sugatoray
