{% set name = "banditpam" %}
{% set version = "3.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/banditpam-{{ version }}.tar.gz
  sha256: c37da853be42dbb19ddf87b288bfaaaabfabdc336805aca5506f35a0837aa35c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy >=1.18
    - pip
    - pybind11 >=2.5.0
    - python
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - banditpam
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ThrunGroup/BanditPAM
  summary: 'BanditPAM: A state-of-the-art, high-performance k-medoids algorithm.'
  license: Apache-2.0
  license_file: headers/carma/LICENSE
  description: |
    Clustering algorithms are ubiquitous in modern data science applications. 
    Compared to the commonly used k-means clustering, k-medoids clustering 
    requires the cluster centers to be actual datapoints and supports arbitrary 
    dissimilarity functions in addition to standard distance metrics. This enables 
    greater interpretability of the cluster centers and the clustering of structured 
    objects. Despite these advantages, k-medoids clustering has been far less 
    popular than k-means due to its computational cost. We present BanditPAM, 
    a randomized algorithm inspired by techniques from multi-armed bandits, that 
    scales almost linearly with dataset size and runs significantly faster than 
    prior algorithms while still matching the best prior algorithms in clustering 
    quality. Prior k-medoids algorithms such as PAM and FastPAM scale quadratically 
    in the dataset size and are significantly slower than k-means, which scales 
    linearly in dataset size. This algorithm, BanditPAM, almost matches k-means 
    in complexity and is significantly faster than prior state-of-the-art with 
    runtime O(nlogn).
    
    PyPI: [https://pypi.org/project/banditpam/](https://pypi.org/project/banditpam/)
    
  doc_url: https://banditpam.readthedocs.io/en/latest/
  dev_url: https://github.com/ThrunGroup/BanditPAM

extra:
  recipe-maintainers:
    - sugatoray
