{% set name = "weaviate-client" %}
{% set version = "2.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/weaviate-client-{{ version }}.tar.gz
  sha256: d7a39e6fcfdc1c32cb1d6903dd4007196108905d8aa9cf7b0dd16f450452a1ae

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - validators
  run:
    - python >=3.6
    - requests >=2.23.0
    - tqdm >=4.59.0
    - validators >=0.18.2

test:
  imports:
    - weaviate
    - weaviate.batch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/weaviate-client/
  summary: A python native weaviate client
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    A python native client for easy interaction with a Weaviate instance.

    The client is tested for python 3.6 and higher.

    Visit the official SeMi Technology website for more information about 
    the Weaviate and how to use it in production.

    Check out our Command Line Interface (CLI) tool for interacting with 
    a Weaviate instance directly from your Terminal.

    PyPI: [https://pypi.org/project/weaviate-client/](https://pypi.org/project/weaviate-client/)

  doc_url: https://weaviate-python-client.readthedocs.io/en/latest/
  dev_url: https://pypi.org/project/weaviate-client/

extra:
  recipe-maintainers:
    - sugatoray
