{% set name = "securesystemslib" %}
{% set version = "0.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/securesystemslib-{{ version }}.tar.gz
  sha256: 573e9c810f2a6afe9ac71a177f26b9d6a321c53574f561f5cef2ed511c3f1831

build:
  number: 0
  noarch: python
  # Grayskull generates the following line
  # skip: true  # [py<37]
  # But we will use "noarch: python" with "python >=3.7"
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - securesystemslib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/secure-systems-lab/securesystemslib
  summary: |
    A library that provides cryptographic and general-purpose 
    routines for Secure Systems Lab projects at NYU
  license: MIT
  license_file:
    - LICENSE
  description: |
    A library that provides cryptographic and general-purpose 
    routines for Secure Systems Lab projects at NYU.

    PyPI: [https://pypi.org/project/securesystemslib/](https://pypi.org/project/securesystemslib/)
  
  doc_url: https://github.com/secure-systems-lab/securesystemslib
  dev_url: https://github.com/secure-systems-lab/securesystemslib

extra:
  recipe-maintainers:
    - sugatoray
