{% set name = "kglab" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kglab-{{ version }}.tar.gz
  sha256: ef71f36c93f5519c206ea2d9637738cf1432a9f80079f890d5cf232638f7c2a6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - chocolate >=0.0.2    
    - decorator >=4.4.2
    - fsspec >=0.8.5
    - gcsfs >=0.7.1
    - gensim >=3.8.3
    - icecream >=2.1
    - matplotlib-base >=3.3.4
    - networkx >=2.6
    - numpy >=1.19.2
    - owlrl >=6.0.2
    - pandas >=1.3
    - pyarrow >=1.0.1
    - pygments >=2.7.4
    - pylev >=1.3
    - pynvml >=8.0.4
    - pyshacl >=0.17.3
    - python-dateutil >=2.8
    - pyvis >=0.1.7.0
    - rdflib >=6.0.2
    - requests >=2.25.1
    - scikit-learn >=0.20.2
    - statsmodels >=0.10.2
    - pytorch >=1.8
    - tqdm >=4.56
    - urlpath >=1.1.7
  run_constrained:
    - csvwlib >=0.3.2
    - pslpython >=2.2.2

test:
  imports:
    - kglab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://derwen.ai/docs/kgl/
  summary: A simple abstraction layer in Python for building knowledge graphs
  license: MIT
  license_file: LICENSE
  description: |
    The kglab package provides a simple 
    [abstraction layer](https://derwen.ai/docs/kgl/glossary/#abstraction-layer) in Python 
    for building [knowledge graphs](https://derwen.ai/docs/kgl/glossary/#knowledge-graph).

    The main goal is to leverage idiomatic Python for common use cases 
    in [data science](https://derwen.ai/docs/kgl/glossary/#data-science) 
    and [data engineering](https://derwen.ai/docs/kgl/glossary/#data-engineering) 
    work that require graph data, presenting 
    [graph data science](https://derwen.ai/docs/kgl/glossary/#graph-data-science) 
    as an emerging practice.

    PyPI: [https://pypi.org/project/kglab/](https://pypi.org/project/kglab/)

  doc_url: https://derwen.ai/docs/kgl/
  dev_url: https://github.com/DerwenAI/kglab/

extra:
  recipe-maintainers:
    - sugatoray
