{% set name = "parsr-client" %}
{% set version = "3.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/parsr-client-{{ version }}.tar.gz
  sha256: ef961b58cc42f6e4c0fa4111d6d940f3c699e0b4fb5d92b01743ed627d1a5113

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - diff-match-patch >=20181111,<20181112
    - pandas >=1.0.3,<2.0.0
    - python >=3.6,<4.0
    - requests >=2.23.0,<3.0.0
    - semver >=2.9.1,<3.0.0
    - sxsdiff >=0.3.0,<0.4.0

test:
  imports:
    - parsr_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/axa-group/Parsr
  summary: Python client for Parsr - Transforms PDF, Documents and Images into Enriched Structured Data
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Provides a python interface to the Parsr tool via its API. Parsr transforms PDF, documents and images into enriched, structured data.

    Find out all about Parsr (including download) at https://github.com/axa-group/Parsr.

    PyPI: [https://pypi.org/project/parsr-client/](https://pypi.org/project/parsr-client/)

  doc_url: https://github.com/axa-group/Parsr/blob/develop/docs/README.md
  dev_url: https://github.com/axa-group/Parsr/tree/develop/clients/python-client

extra:
  recipe-maintainers:
    - sugatoray
