{% set name = "chocolate" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chocolate-{{ version }}.tar.gz
  sha256: 3474af447e11c592635afae2578d8f425351045949dc1c2fd3a98dd859b5816c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - chocolate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/seungjaeryanlee/chocolate
  summary: An improvement to Python's kwargs
  license: MIT
  license_file: LICENSE
  description: |
    **Chocolate** is a Python package that improves Python's `**kwargs`

    PyPI: [https://pypi.org/project/chocolate/](https://pypi.org/project/chocolate/)

  doc_url: https://github.com/seungjaeryanlee/chocolate
  dev_url: https://github.com/seungjaeryanlee/chocolate

extra:
  recipe-maintainers:
    - sugatoray
