{% set name = "evotorch" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/evotorch-{{ version }}.tar.gz
  sha256: bd1f612ef8709e04d59e197aca618bbe579229b13af205d64ecc671535893d57

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - cma
    - gym
    - matplotlib-base
    - numpy
    - pandas
    - ray-default >=1.0
    - pytorch

test:
  imports:
    - evotorch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://evotorch.ai
  summary: EvoTorch is an advanced evolutionary computation library built directly on top of PyTorch, created at NNAISENSE.
  license: Apache-2.0
  license_file:
    - LICENSE
  description: |
    Welcome to the EvoTorch project! EvoTorch is an open source evolutionary computation 
    library developed at [NNAISENSE](https://nnaisense.com/), built on top of [PyTorch](https://pytorch.org/).

    PyPI: [https://pypi.org/project/evotorch/](https://pypi.org/project/evotorch/)

  doc_url: https://docs.evotorch.ai/
  dev_url: https://github.com/nnaisense/evotorch


extra:
  recipe-maintainers:
    - sugatoray
