{% set name = "polars" %}
{% set version = "0.10.14" %}
{% set rust_min_version = "1.52.0" %}
{% set python_min_version = "3.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polars-{{ version }}.tar.gz
  sha256: 8b37f667bae2c894a6f481fbc40c9da24b468762c0dc5fc91e47ccdb296ff93d

build:
  number: 0
  ##noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  ## Rust is available on conda-forge channel:
  ## https://anaconda.org/conda-forge/rust
  build:
    - python                                  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    ##- {{ compiler("rust") }}
    - {{ compiler("c") }}                     # [unix]
    - {{ compiler("m2w64_c") }}               # [win]
    - {{ compiler('rust') }}
    #- rust
    - cargo-bundle-licenses
    - make
  host:
    - pip
    - toml
    - python
    ##- rust >={{ rust_min_version }}
    - maturin
    - setuptools-rust
  run:
    ##- rust >={{ rust_min_version }}
    - numpy
    - python

test:
  imports:
    - polars
  commands:
    - pip check
  requires:
    - pip
    - python
    - pytest
    - rust >={{ rust_min_version }}

about:
  home: https://github.com/pola-rs/polars
  license: MIT
  license_family: MIT
  license_file: https://raw.githubusercontent.com/pola-rs/polars/master/LICENSE
  summary: "Polars is a blazingly fast DataFrames library implemented in Rust using Apache Arrow(2) as memory model."
  doc_url: https://pola-rs.github.io/polars-book/user-guide/index.html
  dev_url: https://github.com/pola-rs/polars

extra:
  recipe-maintainers:
    - sugatoray
