{% set name = "deep-autoviml" %}
{% set version = "0.0.77" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deep_autoviml-{{ version }}.tar.gz
  sha256: 6892283b6d4c9c4f5daf741d40c055e9bed06d995f37bd27435f8c8e7cce18ab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - emoji
    - ipython
    - jupyter
    - matplotlib-base
    - numpy >=1.19.2
    - optuna
    - pandas
    - regex
    - scikit-learn >=0.23.1
    - storm-tuner >=0.0.8
    - tensorflow >=2.5.2
    - tensorflow-hub >=0.12.0    
    - xlrd
  run_constrained:
    - tensorflow-text >=2.5.0

test:
  imports:
    - deep_autoviml
    - deep_autoviml.data_load
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AutoViML/deep_autoviml
  summary: Automatically Build Deep Learning Models and Pipelines fast!
  license: Apache-2.0
  license_file: LICENSE
  description: |
    ✨ deep_autoviml is a powerful new deep learning library with a very simple design goal:  ✨
    
    `Make it easy for novices and experts to experiment and build tensorflow.keras preprocessing 
    pipelines and models in fewest steps.`
    
    But just because we make it easy, does not mean you should trust everything that it does 
    or treat it like a black box. You must still use your own judgement and intutition to make 
    sure the results are accurate and explainable, not to mention that the model conforms to 
    <a href='https://ai.google/principles/'>Responsbile AI principles</a>.


    PyPI: [https://pypi.org/project/deep-autoviml/](https://pypi.org/project/deep-autoviml/)

  doc_url: https://github.com/AutoViML/deep_autoviml
  dev_url: https://github.com/AutoViML/deep_autoviml

extra:
  recipe-maintainers:
    - sugatoray
