{% set name = "whylogs" %}
{% set version = "1.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/whylogs-{{ version }}.tar.gz
  sha256: 3a65fe5e6b77e5fafff9adb86692e9bd128667650c818c53c7b7e556ed356a35

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - flake8 ==4.0.1
    - importlib-metadata >=0.23
    - protobuf >=3.15.5
    - typing-extensions
    - whylogs-sketching >=3.4.1.dev1

test:
  imports:
    - whylogs
    - whylogs.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://docs.whylabs.ai
  summary: Profile and monitor your ML data pipeline end-to-end
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Whylogs is an open source library for logging any kind of data. 
    With whylogs, users are able to generate summaries of their 
    datasets (called _whylogs profiles_) which they can use to:

    1. Track changes in their dataset
    2. Create _data constraints_ to know whether their data looks the way it should
    3. Quickly visualize key summary statistics about their datasets

    PyPI: [https://pypi.org/project/whylogs/](https://pypi.org/project/whylogs/)

  doc_url: https://whylogs.readthedocs.io/
  dev_url: https://github.com/whylabs/whylogs

extra:
  recipe-maintainers:
    - sugatoray
