{% set name = "TSDB" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WenjieDu/TSDB/archive/v{{ version }}.tar.gz
  sha256: 5281edebebe15657a07562c8efe1a57735bc9a51b56b3a8719bccdda43366ff0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - setuptools >=38.6.0
    - python >=3.7
  run:
    - python >=3.7
    - numpy
    - pandas
    - scikit-learn
    - scipy

test:
  imports:
    - tsdb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/WenjieDu/TSDB
  summary: A Python Toolbox to Ease Loading Open-Source Time-Series Datasets
  license: GPL-3.0-only
  license_file:
    - LICENSE
  description: |
    A Python Toolbox to Ease Loading Open-Source Time-Series Datasets.

    PyPI: [https://pypi.org/project/tsdb](https://pypi.org/project/tsdb)

  doc_url: https://github.com/WenjieDu/TSDB
  dev_url: https://github.com/WenjieDu/TSDB

extra:
  recipe-maintainers:
    - sugatoray
