{% set name = "bloxs" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bloxs-{{ version }}.tar.gz
  sha256: f52653a9b33eed38242184487cceb0892777836e92da8bd19014126516395485

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - ipython

test:
  imports:
    - bloxs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mljar/bloxs
  summary: Display data in an attractive way
  license: Apache-2.0
  license_file:
    - LICENSE
  description: |
    # Bloxs

    Bloxs is a simple python package that helps you display information in an 
    attractive way (formed in blocks). Perfect for building dashboards, reports 
    and apps in the notebook.

    It works with: Jupyter Notebook, Google Colab, Deepnote, Kaggle Notebook, 
    [Mercury](https://github.com/mljar/mercury).

    ![gif](https://raw.githubusercontent.com/mljar/visual-identity/main/bloxs/blox-banner.png)

    PyPI: [https://pypi.org/project/bloxs/](https://pypi.org/project/bloxs/)

  doc_url: https://github.com/mljar/bloxs
  dev_url: https://github.com/mljar/bloxs

extra:
  recipe-maintainers:
    - sugatoray
