{% set name = "pygmsh" %}
{% set version = "7.1.17" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygmsh-{{ version }}.tar.gz
  sha256: 563724abff4f8517598d3354b9c795feddbe0675786145bfeaf20cbee6691c1d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - flit-core >=3.2,<4
  run:
    - python >=3.7
    - gmsh
    - meshio >=4.3.2,<6
    - numpy >=1.20.0    

test:
  imports:
    - pygmsh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/meshpro/pygmsh
  summary: Python frontend for Gmsh
  license: GPL-3.0-only
  license_file: LICENSE.txt
  description: |
    pygmsh combines the power of [Gmsh](https://gmsh.info/) with the 
    versatility of Python. It provides useful abstractions from Gmsh's 
    own Python interface so you can create complex geometries more easily.

    PyPI : [https://pypi.org/project/pygmsh/](https://pypi.org/project/pygmsh/)

  doc_url: https://pygmsh.readthedocs.io/en/latest
  dev_url: https://github.com/meshpro/pygmsh

extra:
  recipe-maintainers:
    - sugatoray
