{% set name = "sigstore" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sigstore-{{ version }}.tar.gz
  sha256: e109ecc7a24734215da3627893f0373232637e27688ef0bae4cd6d03ba6e24e5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - cryptography >=3.1
    - pyasn1
    - pyasn1-modules
    - pydantic
    - pyjwt >=2.1
    - pyopenssl
    - requests
    - securesystemslib

test:
  imports:
    - sigstore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sigstore/
  summary: A tool for signing Python package distributions
  license: Apache-2.0
  license_file:
    - LICENSE
  description: |
    `sigstore` is a tool for signing and verifying Python package distributions.

    > NOTE: ⚠️ This project is not ready for general-purpose use! ⚠️

    PyPI: [https://pypi.org/project/sigstore/](https://pypi.org/project/sigstore/)
  
  doc_url: https://github.com/sigstore/sigstore-python
  dev_url: https://github.com/sigstore/sigstore-python

extra:
  recipe-maintainers:
    - sugatoray
