{% set name = "graph4nlp" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graph4nlp-{{ version }}.tar.gz
  sha256: c10071a58a770d32e66578e54da6831432908c90e313b536cb840a1ec55b7b27

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - wheel
  run:
    - python >=3.7
    - networkx >=2.5
    - nltk >=3.5
    - ogb
    - pythonds
    - pyyaml
    - scikit-learn >=0.23.2
    - scipy >=1.5.2
    - stanfordcorenlp
    - tqdm >=4.29.0
    - transformers
  run_constrained:
    - dgl >=0.4

test:
  imports:
    - graph4nlp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/graph4ai/graph4nlp
  summary: A DGL and PyTorch based graph deep learning library for natural language processing
  license: Apache-2.0
  license_file: LICENSE
  description: |
    ***Graph4NLP*** is an easy-to-use library for R&D at the intersection 
    of **Deep Learning on Graphs** and **Natural Language Processing** (i.e., DLG4NLP). 
    It provides both **full implementations** of state-of-the-art models 
    for data scientists and also **flexible interfaces** to build customized 
    models for researchers and developers with whole-pipeline support. 
    Built upon highly-optimized runtime libraries including 
    [DGL](https://github.com/dmlc/dgl) , ***Graph4NLP*** has both high 
    running efficiency and great extensibility. The architecture of 
    ***Graph4NLP*** is shown in the following figure, where boxes with 
    dashed lines represents the features under development. Graph4NLP 
    consists of four different layers: 
    1) Data Layer, 2) Module Layer, 3) Model Layer, and 4) Application Layer.

    <p align="center">
        <img src="https://raw.githubusercontent.com/graph4ai/graph4nlp/master/docs/_images/arch.png" alt="architecture" width="700" />
        <br>
        <b>Figure</b>: Graph4NLP Overall Architecture
    </p>

    PyPI: [https://pypi.org/project/graph4nlp/](https://pypi.org/project/graph4nlp/)

  doc_url: https://dlg4nlp.github.io/index.html
  dev_url: https://github.com/graph4ai/graph4nlp

extra:
  recipe-maintainers:
    - sugatoray
