{% set name = "sxsdiff" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sxsdiff-{{ version }}.zip
  sha256: 416c0e710b7e1efc37c4c5da1f076354b099dc972c07a54c8d6b7bc84fe335a8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python >=2.6
  run:
    - python >=2.6

test:
  imports:
    - sxsdiff
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/timonwong/sxsdiff
  summary: Side by side diff generator for python
  license: BSD-4-Clause
  license_file: LICENSE
  description: |
    Side by side diff generator for python

    PyPI: [https://pypi.org/project/sxsdiff/](https://pypi.org/project/sxsdiff/)

  dev_url: https://github.com/timonwong/sxsdiff

extra:
  recipe-maintainers:
    - sugatoray
