{% set name = "fasttreeshap" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fasttreeshap-{{ version }}.tar.gz
  sha256: 4c740987e390984b198d11cee3ec690264b5ca8a979a01fbff187b11b00d95d2

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
  run:
    - cloudpickle
    - numba
    - packaging >20.9
    - pandas
    - psutil
    - python
    - scikit-learn
    - scipy
    - shap
    - slicer ==0.0.7
    - tqdm >4.25.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - fasttreeshap
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/linkedin/fasttreeshap
  summary: A fast implementation of TreeSHAP algorithm.
  license: BSD-2-Clause
  license_file: LICENSE
  description: |
    `FastTreeSHAP` package implements two new algorithms FastTreeSHAP `v1` 
    and FastTreeSHAP `v2`, to improve the computational efficiency of 
    `TreeSHAP` for large datasets. In practice FastTreeSHAP v1 is 1.5x faster 
    than TreeSHAP while keeping the memory cost unchanged, and FastTreeSHAP v2 
    is 2.5x faster than TreeSHAP at the cost of a slightly higher memory usage.

    PyPI: [https://pypi.org/project/fasttreeshap/](https://pypi.org/project/fasttreeshap/)

  doc_url: http://github.com/linkedin/fasttreeshap
  dev_url: http://github.com/linkedin/fasttreeshap

extra:
  recipe-maintainers:
    - sugatoray
