{% set name = "rasa" %}
{% set version = "3.0.0rc3" %}
{% set build_num = 0 %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d8ef87e706e38efb658cb232b51abb9f97c7d282cfe61314a5187ace28a70150

build:
  skip: True  # [osx or win]
  number: {{ build_num }}

outputs:
  - name: {{ name|lower }}    
    build:
      skip: True  # [osx or win]
      noarch: python
    script: build_base.sh
    requirements:
      {% set pyver = ">=3.7,<3.9" %}
      host:
        - pip
        - python {{ pyver }}
        - poetry-core >=1.0.4
      run:
        - python {{ pyver }}
        - poetry-core >=1.0.4
        # Dependency Source: PKG-INFO:Requires-Dist
        - CacheControl >=0.12.9,<0.13.0
        - PyJWT[crypto] >=2.0.0,<3.0.0
        - SQLAlchemy >=1.3.3,<1.5.0
        - absl-py >=0.9,<0.14
        - aio-pika >=6.7.1,<7.0.0
        - aiohttp >=3.6,<3.8,!=3.7.4.post0
        - apscheduler >=3.6,<3.8
        - async_generator >=1.10,<1.11
        - attrs >=19.3,<21.3
        - boto3 >=1.12,<2.0
        - cloudpickle >=1.2,<1.7
        - colorama >=0.4.4,<0.5.0  # [not win32]
        - colorclass >=2.2,<2.3
        - coloredlogs >=10,<16
        - colorhash >=1.0.2,<1.1.0
        - dask ==2021.7.2
        - fbmessenger >=6.0.0,<6.1.0
        - github3.py >=1.3.0,<1.4.0
        - google-auth >=2.3.3,<3.0.0
        - jieba >=0.39,<0.43
        - joblib >=0.15.1,<1.1.0
        - jsonpickle >=1.3,<2.1
        - jsonschema >=3.2,<3.3
        - kafka-python >=1.4,<3.0
        - keras <2.7.0
        - matplotlib >=3.1,<3.4
        - mattermostwrapper >=2.2,<2.3
        - networkx >=2.4,<2.7
        - numpy >=1.19.2,<1.20.0
        - packaging >=20.0,<21.0
        - prompt-toolkit >=2.0,<3.0
        - psycopg2-binary >=2.8.2,<2.10.0
        - pyTelegramBotAPI >=3.7.3,<4.0.0
        - pydot >=1.4,<1.5
        - pykwalify >=1.7,<1.9
        - pymongo >=3.8,<3.11
        - python-dateutil >=2.8,<2.9
        - python-engineio >=4,<6,!=5.0.0
        - python-socketio >=4.4,<6
        - pytz >=2019.1,<2022.0
        - questionary >=1.5.1,<1.11.0
        - randomname >=0.1.5,<0.2.0
        - rasa-sdk >=3.0.0rc3,<4.0.0
        - redis >=3.4,<4.0
        - regex >=2020.6,<2021.9
        - requests >=2.23,<3.0
        - rocketchat_API >=0.6.31,<1.17.0
        - ruamel.yaml >=0.16.5,<0.17.0
        - sanic >=21.6.0,<22.0.0
        - sanic-cors >=1.0.0,<2.0.0
        - sanic-jwt >=1.6.0,<2.0.0
        - sanic-routing >=0.7.2,<0.8.0
        - scikit-learn >=0.22,<0.25
        - scipy >=1.4.1,<2.0.0
        - sentry-sdk >=0.17.0,<1.4.0
        - setuptools >=41.0.0
        - sklearn-crfsuite >=0.3,<0.4
        - slackclient >=2.0.0,<3.0.0
        - spacy >=3.1,<4.0
        - tarsafe >=0.0.3,<0.0.4
        - tensorflow >=2.6,<2.6.2
        - tensorflow-addons >=0.14,<0.15
        - tensorflow-estimator >=2.6,<2.7
        - tensorflow-probability >=0.11,<0.14
        - tensorflow-text >=2.6,<2.7  # [not win32]
        - tensorflow_hub >=0.10,<0.13
        - terminaltables >=3.1.0,<3.2.0
        - tqdm >=4.31,<5.0
        - transformers >=2.4,<2.12
        - twilio >=6.26,<6.51
        - typing-extensions >=3.7.4,<4.0.0
        - typing-utils >=0.1.0,<0.2.0
        - ujson >=1.35,<5.0
        - webexteamssdk >=1.1.1,<1.7.0
      #run_constrained:
        
    test:
      imports:
        - {{ name|lower }}
      commands:
        - pip check
      requires:
        - pip


about:
  home: https://rasa.com/
  summary: |
    Open source machine learning framework to automate text 
    and voice-based conversations: NLU, dialogue management, 
    connect to Slack, Facebook, and more - Create chatbots 
    and voice assistants.
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |
    Rasa is an open source machine learning framework to automate text-
    and voice-based conversations. With Rasa, you can build contextual 
    assistants on,    
      - Facebook Messenger
      - Slack
      - Google Hangouts
      - Webex Teams
      - Microsoft Bot Framework
      - Rocket.Chat
      - Mattermost
      - Telegram
      - Twilio
      - Your own custom conversational channels    
    or voice assistants as,
      - Alexa Skills
      - Google Home Actions
    Rasa helps you build contextual assistants capable of having layered 
    conversations with lots of back-and-forth. In order for a human to 
    have a meaningful exchange with a contextual assistant, the assistant 
    needs to be able to use context to build on things that were previously 
    discussed – Rasa enables you to build assistants that can do this in 
    a scalable way.    
  doc_url: https://rasa.com/docs
  dev_url: https://github.com/RasaHQ/rasa/

extra:
  recipe-maintainers:
    - sugatoray
    #- koaning
  feedstock-name: {{ name|lower }}
