{% set name = "rasa" %}
{% set version = "3.0.0rc3" %}
{% set build_num = 0 %}

{% set libs = {
    "python": {
      "name": "python",
      "version": ">=3.7,<3.9"
    },
    "boto3": {
      "name": "boto3",
      "version": "^1.12"
    },
    "requests": {
      "name": "requests",
      "version": "^2.23"
    },
    "matplotlib": {
      "name": "matplotlib",
      "version": ">=3.1,<3.4"
    },
    "attrs": {
      "name": "attrs",
      "version": ">=19.3,<21.3"
    },
    "jsonpickle": {
      "name": "jsonpickle",
      "version": ">=1.3,<2.1"
    },
    "redis": {
      "name": "redis",
      "version": "^3.4"
    },
    "numpy": {
      "name": "numpy",
      "version": ">=1.19.2,<1.20.0"
    },
    "scipy": {
      "name": "scipy",
      "version": "^1.4.1"
    },
    "absl-py": {
      "name": "absl-py",
      "version": ">=0.9,<0.14"
    },
    "apscheduler": {
      "name": "apscheduler",
      "version": ">=3.6,<3.8"
    },
    "tqdm": {
      "name": "tqdm",
      "version": "^4.31"
    },
    "networkx": {
      "name": "networkx",
      "version": ">=2.4,<2.7"
    },
    "fbmessenger": {
      "name": "fbmessenger",
      "version": "~6.0.0"
    },
    "pykwalify": {
      "name": "pykwalify",
      "version": ">=1.7,<1.9"
    },
    "coloredlogs": {
      "name": "coloredlogs",
      "version": ">=10,<16"
    },
    "ruamel.yaml": {
      "name": "ruamel.yaml",
      "version": "^0.16.5"
    },
    "scikit-learn": {
      "name": "scikit-learn",
      "version": ">=0.22,<0.25"
    },
    "slackclient": {
      "name": "slackclient",
      "version": "^2.0.0"
    },
    "twilio": {
      "name": "twilio",
      "version": ">=6.26,<6.51"
    },
    "webexteamssdk": {
      "name": "webexteamssdk",
      "version": ">=1.1.1,<1.7.0"
    },
    "mattermostwrapper": {
      "name": "mattermostwrapper",
      "version": "~2.2"
    },
    "rocketchat_API": {
      "name": "rocketchat_API",
      "version": ">=0.6.31,<1.17.0"
    },
    "colorhash": {
      "name": "colorhash",
      "version": "~1.0.2"
    },
    "jsonschema": {
      "name": "jsonschema",
      "version": "~3.2"
    },
    "packaging": {
      "name": "packaging",
      "version": ">=20.0,<21.0"
    },
    "pytz": {
      "name": "pytz",
      "version": ">=2019.1,<2022.0"
    },
    "rasa-sdk": {
      "name": "rasa-sdk",
      "version": "^3.0.0rc3"
    },
    "colorclass": {
      "name": "colorclass",
      "version": "~2.2"
    },
    "terminaltables": {
      "name": "terminaltables",
      "version": "~3.1.0"
    },
    "sanic": {
      "name": "sanic",
      "version": "^21.6.0"
    },
    "sanic-cors": {
      "name": "sanic-cors",
      "version": "^1.0.0"
    },
    "sanic-jwt": {
      "name": "sanic-jwt",
      "version": "^1.6.0"
    },
    "cloudpickle": {
      "name": "cloudpickle",
      "version": ">=1.2,<1.7"
    },
    "aiohttp": {
      "name": "aiohttp",
      "version": ">=3.6,<3.8,!=3.7.4.post0"
    },
    "questionary": {
      "name": "questionary",
      "version": ">=1.5.1,<1.11.0"
    },
    "prompt-toolkit": {
      "name": "prompt-toolkit",
      "version": "^2.0"
    },
    "python-socketio": {
      "name": "python-socketio",
      "version": ">=4.4,<6"
    },
    "python-engineio": {
      "name": "python-engineio",
      "version": ">=4,<6,!=5.0.0"
    },
    "pydot": {
      "name": "pydot",
      "version": "~1.4"
    },
    "async_generator": {
      "name": "async_generator",
      "version": "~1.10"
    },
    "SQLAlchemy": {
      "name": "SQLAlchemy",
      "version": ">=1.3.3,<1.5.0"
    },
    "sklearn-crfsuite": {
      "name": "sklearn-crfsuite",
      "version": "~0.3"
    },
    "psycopg2-binary": {
      "name": "psycopg2-binary",
      "version": ">=2.8.2,<2.10.0"
    },
    "python-dateutil": {
      "name": "python-dateutil",
      "version": "~2.8"
    },
    "tensorflow": {
      "name": "tensorflow",
      "version": ">=2.6,<2.6.2"
    },
    "tensorflow_hub": {
      "name": "tensorflow_hub",
      "version": ">=0.10,<0.13"
    },
    "tensorflow-addons": {
      "name": "tensorflow-addons",
      "version": "~0.14"
    },
    "tensorflow-estimator": {
      "name": "tensorflow-estimator",
      "version": "~2.6"
    },
    "tensorflow-probability": {
      "name": "tensorflow-probability",
      "version": ">=0.11,<0.14"
    },
    "setuptools": {
      "name": "setuptools",
      "version": ">=41.0.0"
    },
    "kafka-python": {
      "name": "kafka-python",
      "version": ">=1.4,<3.0"
    },
    "ujson": {
      "name": "ujson",
      "version": ">=1.35,<5.0"
    },
    "regex": {
      "name": "regex",
      "version": ">=2020.6,<2021.9"
    },
    "joblib": {
      "name": "joblib",
      "version": ">=0.15.1,<1.1.0"
    },
    "sentry-sdk": {
      "name": "sentry-sdk",
      "version": ">=0.17.0,<1.4.0"
    },
    "aio-pika": {
      "name": "aio-pika",
      "version": "^6.7.1"
    },
    "pyTelegramBotAPI": {
      "name": "pyTelegramBotAPI",
      "version": "^3.7.3"
    },
    "dask": {
      "name": "dask",
      "version": "2021.7.2"
    },
    "typing-extensions": {
      "name": "typing-extensions",
      "version": "^3.7.4"
    },
    "typing-utils": {
      "name": "typing-utils",
      "version": "^0.1.0"
    },
    "tarsafe": {
      "name": "tarsafe",
      "version": "^0.0.3"
    },
    "google-auth": {
      "name": "google-auth",
      "version": "^2.3.3"
    },
    "CacheControl": {
      "name": "CacheControl",
      "version": "^0.12.9"
    },
    "randomname": {
      "name": "randomname",
      "version": "^0.1.5"
    },
    "keras": {
      "name": "keras",
      "version": "<2.7.0"
    },
    "sanic-routing": {
      "name": "sanic-routing",
      "version": "^0.7.2"
    }
  } %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d8ef87e706e38efb658cb232b51abb9f97c7d282cfe61314a5187ace28a70150

build:
  skip: True  # [osx or win]
  # noarch: python
  number: {{ build_num }}
  # script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed && \
  #         export PACKAGE_REQUIREMENTS_SPEC=$(python fetch_requirements.py -p "requirements.txt" -v) && \
  #         echo -e "\n\tPACKAGE_REQUIREMENTS_SPEC = "$PACKAGE_REQUIREMENTS_SPEC"\n"
  # script_env:
  #   - PACKAGE_REQUIREMENTS_SPEC

outputs:
  - name: {{ name|lower }}    
    build:
      skip: True  # [osx or win]
      noarch: python
      #script_env:
        # ref: https://python-packaging-tutorial.readthedocs.io/en/latest/conda.html#loading-arbitrary-data
        #- PACKAGE_REQUIREMENTS_SPEC={{ load_file_regex(load_file="libspec.yaml", regex_pattern=".*") }}
    script: build_base.sh
    requirements:
      ##{#% set libs = environ.get("PACKAGE_REQUIREMENTS_SPEC", {}) %#}
      {% set pyver = libs.get("python", {}).get("version", ">=3.7,<3.9") %}
      host:
        - pip
        - python {{ pyver }}
      run:
        - python {{ pyver }}
      run_constrained:
        {% for libname, libspec in libs.items() %}   
        {% if libname|lower != "python" %}
        - {{ libname }} {{ libspec.get("version") }}
        {% endif %}
        {% endfor %}
    test:
      imports:
        - {{ name|lower }}
      commands:
        - pip check
      requires:
        - pip


about:
  home: https://rasa.com/
  summary: |
    Open source machine learning framework to automate text 
    and voice-based conversations: NLU, dialogue management, 
    connect to Slack, Facebook, and more - Create chatbots 
    and voice assistants.
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |
    Rasa is an open source machine learning framework to automate text-
    and voice-based conversations. With Rasa, you can build contextual 
    assistants on,    
      - Facebook Messenger
      - Slack
      - Google Hangouts
      - Webex Teams
      - Microsoft Bot Framework
      - Rocket.Chat
      - Mattermost
      - Telegram
      - Twilio
      - Your own custom conversational channels    
    or voice assistants as,
      - Alexa Skills
      - Google Home Actions
    Rasa helps you build contextual assistants capable of having layered 
    conversations with lots of back-and-forth. In order for a human to 
    have a meaningful exchange with a contextual assistant, the assistant 
    needs to be able to use context to build on things that were previously 
    discussed – Rasa enables you to build assistants that can do this in 
    a scalable way.    
  doc_url: https://rasa.com/docs
  dev_url: https://github.com/RasaHQ/rasa/

extra:
  recipe-maintainers:
    - sugatoray
    #- koaning
  feedstock-name: {{ name|lower }}
  #libs: {#% include libspec.yaml %#}
