{% set name = "ydata-synthetic" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ydata-synthetic-{{ version }}.tar.gz
  sha256: 8e14f945d3c2202a6bff2f803ef01c278c19d1b0bccf9f715ef2344420795472

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<3.9
  run:
    - python >=3.6,<3.9
    - easydict ==1.9
    - matplotlib-base ==3.3.2
    - numpy >=1.19.0,<1.20.0
    - pandas ==1.2.0
    - pmlb ==1.0.*
    - pytest ==6.2.*
    - scikit-learn ==1.0.*
    - seaborn ==0.11.*
    - tensorflow ==2.4.*
    - tqdm <5.0.0
    - typeguard ==2.13.*
    ## Necessary for passing pip-check
    - absl-py >=0.10.0,<0.11.0
    - wrapt >=1.12.1,<1.13.0

test:
  imports:
    - ydata_synthetic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ydataai/ydata-synthetic
  summary: Synthetic data generation methods with different synthetization methods.
  license: GPL-3.0-or-later
  license_file: LICENSE
  description: |
    This repository contains material related with Generative Adversarial Networks for 
    synthetic data generation, in particular regular tabular data and time-series. It 
    consists a set of different GANs architectures developed using Tensorflow 2.0. 
    Several example Jupyter Notebooks and Python scripts are included, to show how to 
    use the different architectures.

    PyPI: [https://pypi.org/project/ydata-synthetic/](https://pypi.org/project/ydata-synthetic/)

  doc_url: https://github.com/ydataai/ydata-synthetic
  dev_url: https://github.com/ydataai/ydata-synthetic

extra:
  recipe-maintainers:
    - sugatoray
